### ISSUE TITLE
Warning: Exited with error code 5 Use --force to continue.

### ISSUE THREAD

**Issue by Drosen** [CodeCatalyst/grunt-sketch#2]
I am trying to run the grunt task exactly as shown in the example -  output files are created but appear in the src/ directory, not in my dest directory.

the process returns error code 5 and I see a few error messages:

sketchtool[95057] <Error>: The function `CGContextClear' is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.

also:

"Couldn't read document file:///Users/xxxx/code/web/Projects/svgSprite_test/build/assets/."
"Failed to open document build/assets/ -- file:///Users/xxxx/code/web/Projects/svgSprite_test/"

using sketchtool Version 1.2 (196)
Sketch 3.04

**Comment by johnyanarella** [comment]
A big thank you to @mjgreen145 for tracking down that issue with the documentation and helping others get up and running.

Pushed an update today that includes his update to the README and adds support for new options recently added to SketchTool (and updates the Travis CI configuration and test suite for better forward compatibility).
