### ISSUE TITLE
Use `sketchjs` to slim down the project

### ISSUE THREAD

**Issue by iDuuck** [CodeCatalyst/grunt-sketch#7]
How about using my package [`sketchjs`](https://travis-ci.org/iDuuck/sketchjs/builds/117937554) for this?

**Comment by johnyanarella** [comment]
That's a neat little wrapper package.

That said, I'm not sure I want to introduce another dependency to this project, and the supported parameters / features don't fully line up with how things work under the hood in `grunt-sketch`.

Definitely can imagine some other uses cases where `sketchjs` will be useful - thanks for mentioning it!
