### ISSUE TITLE
Multiple File SRC

### ISSUE THREAD

**Issue by F1LT3R** [CodeCatalyst/grunt-sketch#8]
You don't seem to be able to export slices from multiple sources with this tool.

Am I missing something?

**Comment by johnyanarella** [comment]
Thanks for reporting this issue.

The upcoming `1.0.5` release will include refactored handling of the Grunt `files` processing logic to ensure all of the standard [Grunt-supported file formats](https://gruntjs.com/configuring-tasks#files) are supported by `grunt-sketch`.

This includes wildcards, `files` object format with multiple src-dest mappings, etc.

**Comment by johnyanarella** [comment]
`1.0.5` has been released and includes a fix for this issue.
