### ISSUE TITLE
README.md code example falsely features type `layers`

### ISSUE THREAD

**Issue by Volker-E** [CodeCatalyst/grunt-sketch#9]
`layers` seems to be unsupported with current npm version 1.0.2
1.0.4 has never been released on npm: https://www.npmjs.com/package/grunt-sketch

**Comment by johnyanarella** [comment]
Thanks for reporting this issue. It looks like it isn't supported in `1.0.4`, either. (Just published that version as well - thanks for point that out, too!)

`layers` was accidentally omitted from the command-line parsing logic for that parameter.

I'll get `1.0.5` out shortly with a fix for the `layers` option.

**Comment by johnyanarella** [comment]
`1.0.5` has been released and includes a fix for this issue.
